--문자열 함수
--LOWER()소문자로, INITCAP()첫글자만 대문자, UPPER()대문자로
SELECT LOWER('HELLO'), INITCAP('HELLO'), UPPER('HELLO') FROM DUAL; -- DUAL은 가상테이블
SELECT LOWER(FIRST_NAME), INITCAP(FIRST_NAME), UPPER(FIRST_NAME) FROM EMPLOYEES;

--함수는 WHERE절에도 적용됩니다.
SELECT FIRST_NAME FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'STEVEN';

--LENGTH()길이, INSTR()문자찾기
SELECT FIRST_NAME, LENGTH(FIRST_NAME),INSTR(FIRST_NAME,'e') FROM EMPLOYEES;

--SUBSTR()문자열자르기, CONCAT()문자열합치기
SELECT FIRST_NAME, SUBSTR(FIRST_NAME,1,3) FROM EMPLOYEES; -- 1번째에서 3번째글자를 출력
SELECT FIRST_NAME, CONCAT(FIRST_NAME,LAST_NAME) FROM EMPLOYEES; -- FIRST,LAST NAME을 합쳐서 출력 ||과 동일

--LPAD()왼쪽 채우기, RPAD()오른쪽 채우기
SELECT LPAD('HELLO',10,'*') FROM DUAL; -- 10칸잡고 빈칸이있으면 왼쪽부터 채움
SELECT LPAD(SALARY,10,'*') FROM EMPLOYEES; 
SELECT RPAD(SALARY,10,'-') FROM EMPLOYEES; --오른쪽부터 채움

--LTRIM()왼쪽 제거, RTRIM()오른쪽 제거, TRIM()양쪽모두 제거
SELECT LTRIM('   HELLO') FROM DUAL;
SELECT FIRST_NAME,LTRIM(FIRST_NAME,'A') FROM EMPLOYEES; -- 왼쪽에 처음발견되는 문자 제거
SELECT RTRIM('   HELLO  ')AS RESULT FROM DUAL;
SELECT TRIM('    HELLO    ')FROM DUAL;

--REPLACE()문자열 변경
SELECT REPLACE('HELLO WORLD','HELLO','BYE') FROM DUAL; -- (출력문자열, 바꾸고싶은 단어, 변경할단어)
SELECT REPLACE('HELLO WORLD ~!', ' ','') FROM DUAL; --모든 공백 제거

--중첩
SELECT REPLACE('HELLO WORLD ~!', 'HELLO','BYE') FROM DUAL;
SELECT REPLACE(REPLACE('HELLO WORLD ~!', 'HELLO','BYE'), ' ','') FROM DUAL;